{
  imports = [
    ./bmofetch.nix
    ./dunst.nix
    ./git.nix
    ./gtk.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./hyprcursor.nix
    ./hyprgrass.nix
    ./hyprpaper.nix
    ./kitty.nix
    ./nixvim.nix
    ./pretty-proto.nix
    ./rofi.nix
    ./stylix.nix
    ./waybar.nix
  ];
}
